# ======================================================================================
# Copyright and other protections apply. Please see the accompanying LICENSE file for
# rights and restrictions governing use of this software. All rights not expressly
# waived or licensed are reserved. If that file is missing or appears to be modified
# from its original, then please contact the author before viewing or using this
# software in any capacity.
# ======================================================================================

[project]
name = "dyceum"
dynamic = ["version"]
description = "Interactivity tools for dyce"
readme = {file = "README.md", content-type = "text/markdown; charset=UTF-8"}
license = "MIT"
license-files = ["LICENSE"]
authors = [{name = "Matt Bogosian", email = "matt@bogosian.net"}]
requires-python = ">=3.11"
dependencies = [
    "dyce~=0.7.0rc11",
    "lark>=1.3.1",
    "typing_extensions>=4.5; python_version < '3.13'",  # back-port of deprecated decorator
]
classifiers = [
  "Topic :: Education",
  "Topic :: Games/Entertainment",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Homepage = "https://dyceum.org/"
"Source Repository" = "https://github.com/posita/dyceum/"

[project.optional-dependencies]
jupyter = ["dyce[viz-mpl]", "ipywidgets"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dyceum", "dyceum.anydice"]
package-data = {"dyceum" = ["anydice/grammar.lark", "py.typed"]}

[tool.setuptools_scm]
fallback_version = "0.0.0+unknown"

[dependency-groups]
dev = [
    {include-group = "docs"},
    {include-group = "jupyter"},
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "tox"},
]
# Only what's needed for uv run zensical build
docs = [
    "griffe-warnings-deprecated",
    "jupyter-server",
    "jupyterlab-server",
    "jupyterlab-widgets",
    "jupytext",
    "jupyterlite",
    "jupyterlite-pyodide-kernel",
    "markdown-pycon",  # syntax highlighting for doctests
    "mike @ git+https://github.com/squidfunk/mike.git",
    "mkdocstrings[python]",
    "pandas",
    "pandas-stubs",
    "pymdown-extensions",
    "zensical",
    {include-group = "jupyter"},
]
# Mirrors optional dependencies
jupyter = ["dyce[viz-mpl]", "ipywidgets"]
# Only what's needed for uv run pre-commit run --all-files --hook-stage pre-push
lint = [
    "matplotlib_inline",
    "mypy",
    "pre-commit",
    "pre-commit-uv",
    "pyright",
    "pytest",
    "ruff",
    "ty",
    "zuban",
    {include-group = "docs"},
]
# Only what's needed for quickstart-local.sh
quickstart = [
    "uv",
    {include-group = "docs"},
]
# Only what's needed for uv run pytest --cov
test = [
    "coverage[toml]",
    "pandas",
    "pytest-cov",
    {include-group = "jupyter"},
    {include-group = "test-pypy"},
]
test-beartype = [
    "beartype>=0.23.0rc0",
    {include-group = "test"},
]
# Only what's needed for uv run pytest specifically with PyPy (via Tox)
test-pypy = [
    "griffe-warnings-deprecated",
    "ipdb",
    "pytest",
]
# Only what's needed for uv run tox [-e ...]
tox = [
    "tox",
    "tox-uv",
]

[tool.codespell]
# Suggested pronunciations. (See WBO guides in
# <https://en.wikipedia.org/wiki/Pronunciation_respelling_for_English#Traditional_respelling_systems>.)
# - Nd: ehn-DEE
# - countin: Shucks! Jes' lahk i'sez, pahdnah!
# - damange: duh-MAYNJ
ignore-words-list = "Nd,countin,damange"
skip = ["*.ipynb"]

[tool.coverage.run]
source = ["dyceum"]
branch = true

[tool.coverage.report]
show_missing = true

[tool.mypy]
files = ["dyceum", "docs", "docs-src", "helpers", "tests", "*.py"]
# exclude = """(?x)(
#     ^docs-src/nb_.*\\.py$
# )"""
exclude_gitignore = true
python_version = "3.11"
strict = true
# warn_redundant_casts = true  # included in strict
warn_unreachable = true
# warn_unused_configs = true  # included in strict
# warn_unused_ignores = true  # included in strict

[warnings]
unused-ignore = true

[tool.pyright]
include = ["dyceum", "docs", "docs-src", "helpers", "tests", "*.py"]
pythonVersion = "3.11"
reportUnnecessaryTypeIgnoreComment = "warning"
typeCheckingMode = "basic"

[tool.pytest.ini_options]
addopts = [
  "--doctest-glob=*.md",
  "--doctest-modules",
  "--durations=4",
  "--pdbcls=IPython.terminal.debugger:TerminalPdb",
]
doctest_optionflags = [
  # See <https://docs.python.org/3/library/doctest.html#option-flags>
  "ELLIPSIS",
  "IGNORE_EXCEPTION_DETAIL",
  "NORMALIZE_WHITESPACE",
  # See also <https://docs.pytest.org/en/stable/how-to/doctest.html#using-doctest-options>
  "NUMBER",
]
testpaths = ["README.md", "dyceum", "docs", "docs-src", "helpers", "tests", "*.py"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.per-file-ignores]
"dyceum/magic.py" = [
  "print",  # `print` is the Jupyter cell-output mechanism
]
"docs-src/nb_*.py" = [
  # Allow co-mingled imports for snippets
  "module-import-not-at-top-of-file",  # Module level import not at top of file
  # ruff is confused by jupytext comments
  "commented-out-code",  # Found commented-out code
  # Cells support `await` statements
  "yield-outside-function",  # `await` statement outside of a function
  "await-outside-async",  # `await` should be used within an async function
  # Useful for cell display
  "useless-expression",   # Found useless expression
  "print",  # `print` found (eglot-check)
  # Catch-all for things that are only ignored in these files
  "unused-noqa",  # Unused `noqa` directive ...
]
"docs-src/plot_*.py" = [
  # Allow co-mingled imports for snippets
  "module-import-not-at-top-of-file",  # Module level import not at top of file
  # Useful for cell display
  "useless-expression",   # Found useless expression
  "print",  # `print` found (eglot-check)
]
"docs/notebooks/*.ipynb" = [
  "module-import-not-at-top-of-file",  # Module level import not at top of file
  # Useful for cell display
  "useless-expression",   # Found useless expression
  "print",  # `print` found (eglot-check)
]
"helpers/anydice-programs.py" = [
  "complex-structure",  # `...` is too complex
  "print",  # `print` found (eglot-check)
]

[tool.ruff.lint]
preview = true
ignore = [
  "CPY",
  "D",
  "DOC",
  "EM",
  "FIX",  # TODO(posita): run occasionally, or figure out how to make these warnings
  "PLC",
  "PLR",
  "missing-trailing-comma",  # Trailing comma missing
  "line-too-long",  # Line too long (... > ...)
  "implicit-namespace-package",  # File ... is part of an implicit namespace package. Add an `__init__.py`.
  "non-lowercase-variable-in-function",  # Variable ... in function should be lowercase
  "superfluous-else-return",  # Unnecessary `else` after `return` statement
  "superfluous-else-raise",  # Unnecessary `else` after `raise` statement
  "superfluous-else-continue",  # Unnecessary `else` after `continue` statement
  "ambiguous-unicode-character-docstring",  # Docstring contains ambiguous ...
  "non-empty-init-module",  # `__init__` module should only contain docstrings and re-exports
  "assert",  # Use of `assert` detected
  "suspicious-non-cryptographic-random-usage",  # Standard pseudo-random generators are not suitable for cryptographic purposes
  "raise-vanilla-args",  # Avoid specifying long messages outside the exception class
]
select = [
  "ALL",
]

[tool.ty.src]
include = ["dyceum", "docs", "docs-src", "helpers", "tests", "*.py"]
exclude = ["docs-src/nb_*.py"]

[tool.zuban]
files = ["dyceum", "docs", "docs-src", "helpers", "tests", "*.py"]
# exclude = """(?x)(
#     ^docs-src/nb_.*\\.py$
# )"""
exclude_gitignore = true
python_version = "3.11"
strict = true
# warn_redundant_casts = true  # included in strict
warn_unreachable = true
# warn_unused_configs = true  # included in strict
# warn_unused_ignores = true  # included in strict

[tool.check_doctests]
# log_level = "DEBUG"

[tool.check_doctests.check]
checkers = [
  ["ty", "check"],
  ["zuban", "check"],
  ["pyright"],
  ["mypy"],
]
fail_fast = false
